name: lint, test, build checks.
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  pipeline:
    runs-on: [ubuntu-latest, macos-latest]
    strategy:
      matrix:
        node: [ 16.x ]

    steps:
      - name: Checkout Commit
      uses: actions/checkout@v2
      - name: Starting Node.js ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
      - name: Install node modules
        run: npm install
      - name: Build app
        run: npm run build:prod
      - name: Lint ts-check
        run: npm run lint:ts
      - name: Lint css-check
        run: npm run lint:scss
      - name: Unit-test-check
        run: npm run test:unit
